feat: support classic ingest keys
honeycombio/libhoney-dotnet pull request #96
Opened 2024-03-01 13:34 UTC by brookesargent

## Which problem is this PR solving?

-

## Short description of the changes

-

2024-03-01 15:16 UTC, cewkrupa approved these changes
Testing this change the same way the isClassic check was being tested before makes sense if we're keeping it a private method! I could still be convinced to make it a public method, but this seems perfectly fine to me

2024-03-04 12:59 UTC, MikeGoldsmith requested changes
The new function looks good. I've added a commit to make the `IsClassic` function internal and then exposed it to the test project using the `InternalsVisbleTo` directive. This means the function isn't public for consumers to see / use and can be tested.

If you could add some tests `IsClassic` like we have for the other libhoney's, that would be great.

2024-03-04 14:08 UTC, brookesargent commented
> The new function looks good. I've added a commit to make the `IsClassic` function internal and then exposed it to the test project using the `InternalsVisbleTo` directive. This means the function isn't public for consumers to see / use and can be tested.
> 
> If you could add some tests `IsClassic` like we have for the other libhoney's, that would be great.

Thanks for your help, Mike! Just pushed up some direct tests for `IsClassic`

2024-03-04 14:20 UTC, MikeGoldsmith approved these changes
Looks good 👍🏻

2024-03-04 15:13 UTC, merged